const x = 10

try{
    x = x * 2
}catch (erro) { 
    console.log(`Algo deu errado: ${erro}`)
}